Table users {
  id biginteger [PK, increment]
  name varchar
  email varchar
  password varchar
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table peternakan { // auditable
  id biginteger [PK, increment]
  nama varchar
  lokasi varchar
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table strain { // auditable
  id biginteger [PK, increment]
  nama varchar
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table strain_standart_metric {
  id biginteger // auditable
  strain_id biginteger [Ref : > strain.id]
  umur decimal [note: 'minggu']
  berat_badan_min decimal [note: 'gram']
  berat_badan_max decimal [note: 'gram']
  berat_badan decimal [note: 'gram']
  persentase_kematian decimal
  feed_intake decimal
  fcr decimal
  hdp decimal
  hhp decimal
  egg_weight decimal [note: 'gram per butir']
  egg_mass decimal [note: 'gram per ekor per hari']
  created_at timestamp
  updated_at timestamp
}

Table kandang { // auditable
  id biginteger [PK, increment]
  peternakan_id biginteger [Ref : > peternakan.id]
  strain_id biginteger [Ref : > strain.id]
  nama varchar
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table flock { // auditable
  id biginteger [PK, increment]
  kandang_id biginteger [Ref : > kandang.id]
  nama varchar
  kapasitas integer
  created_at timestamp
  updated_at timestamp
}

Table pipe { // auditable
  id biginteger [PK, increment]
  flock_id int [Ref : > flock.id]
  nama varchar
  kapasitas decimal
  created_at timestamp
  updated_at timestamp
}

Table pengadaan_ayam { // auditable
  id biginteger [PK, increment]
  pic_user_id biginteger [Ref : > users.id]
  tanggal datetime
  umur_ayam integer [note: 'dalam satuan minggu']
  kondisi_ayam varchar
  jumlah_ayam_datang integer
  jumlah_ayam_mati integer
  jumlah_ayam_sakit integer
  jumlah_ayam_masuk_kandang integer
  catatan text [null]
  created_at timestamp
  updated_at timestamp
}

Table pengadaan_ayam_berkas_supplier { // auditable
  id biginteger [PK, increment]
  pengadaan_ayam_id biginteger [Ref : > pengadaan_ayam.id]
  nama_berkas varchar [note: 'surat jalan; data berat; uniformity; rekam kesehatan; vaksin; dll']
  filepath varchar
  created_at timestamp
  updated_at timestamp
}

Table pengadaan_ayam_dokumentasi { // auditable
  id biginteger [PK, increment]
  pengadaan_ayam_id biginteger [Ref : > pengadaan_ayam.id]
  filepath varchar [note: 'file foto']
  created_at timestamp
  updated_at timestamp
}

Table pengadaan_ayam_distribusi { // auditable
  id biginteger [PK, increment]
  pengadaan_ayam_id biginteger [Ref : > pengadaan_ayam.id]
  pipe_id biginteger [Ref : > pipe.id]
  jumlah_ayam integer
  created_at timestamp
  updated_at timestamp
}

Table populasi_ayam {
  id biginteger [PK, increment] // auditable
  pengadaan_ayam_distribusi_id biginteger [Ref : > pengadaan_ayam_distribusi.id]
  jenis_pemeriksaan enum // pengadaan, pencatatan_populasi_harian, pengecekan_kesehatan
  pic_user_id biginteger [Ref : > users.id]
  tanggal datetime
  pipe_id biginteger
  umur_ayam_record integer
  ayam_sehat integer [null]
  ayam_mati integer
  ayam_afkir integer
  ayam_masuk_karantina integer
  ayam_keluar_karantina integer
  catatan text
  created_at timestamp
  updated_at timestamp
}

Table karantina_populasi {
  id biginteger [PK, increment]
  kandang_id biginteger [Ref : > kandang.id]
  pic_user_id biginteger [Ref : > users.id]
  // populasi_ayam_id biginteger [null]
  total_ayam_karantina integer
  tanggal datetime
  ayam_mati integer
  ayam_afkir integer
  pemberian_pakan decimal
  sisa_pakan decimal
  jumlah_telur_bagus integer
  jumlah_telur_retak integer
  jumlah_telur_rusak integer
  berat_telur_bagus decimal
  berat_telur_retak decimal
  berat_telur_rusak decimal
  pengobatan_yang_dilakukan varchar
  jumlah_ayam_diobati integer
  penyemprotan varchar
  vaksin varchar
  catatan text
  created_at timestamp
  updated_at timestamp
}

Table karantina_populasi_pipe {
  id biginteger [PK, increment]
  populasi_ayam_asal_id biginteger [Ref : > populasi_ayam.id]
  tanggal date
  pipe_asal_id biginteger [Ref : > pipe.id]
  ayam_masuk_karantina integer
  pipe_tujuan_id biginteger [Ref : > pipe.id]
  ayam_keluar_karantina integer
}

Table ayam_afkir_populasi {
  id biginteger [PK, increment]
  ayam_afkir_id biginteger [Ref : > ayam_afkir.id]
  populasi_ayam_id biginteger [Ref : > populasi_ayam.id]
  pipe_id biginteger [Ref : > pipe.id]
  flock_id biginteger [Ref : > flock.id]
  kandang_id biginteger [Ref : > kandang.id]
  pic_user_id biginteger [Ref : > users.id]
  tanggal datetime
  jumlah_ayam_afkir decimal
  created_at timestamp
  updated_at timestamp
}

Table ayam_afkir {
  id biginteger [PK, increment]
  kandang_id biginteger [Ref : > kandang.id]
  tanggal datetime
  umur_ayam integer
  penyebab_afkir varchar
  pembeli_afkir varchar
  harga_jual decimal
  created_at timestamp
  updated_at timestamp
}

Table jenis_pakan {
  id biginteger [PK, increment]
  nama varchar
  created_at timestamp
  updated_at timestamp
}

Table perhitungan_pakan {
  id biginteger [PK, increment]
  tanggal_pemberian_pakan date
  umur_ayam int
  user_creator_id biginteger [Ref : > users.id] // spv kandang
  user_executor_id biginteger [Ref : > users.id]
  jenis_pakan_id biginteger [Ref : > jenis_pakan.id]
  kandang_id biginteger [Ref : > kandang.id]
  proporsi_pemberian_pagi decimal(10,3)
  proporsi_pemberian_sore decimal(10,3)
  waktu_pemberian_pagi time
  waktu_pemberian_sore time
  catatan text
  created_at timestamp
  updated_at timestamp
}

Table perhitungan_pakan_item {
  id biginteger [PK, increment]
  perhitungan_pakan_id biginteger [Ref : > perhitungan_pakan.id]
  kandang_id int [Ref : > kandang.id]
  flock_id int [Ref : > flock.id]
  pipe_id int [Ref : > pipe.id]
  tanggal_pemberian_pakan date
  jumlah_ayam int
  pemberian_pakan_per_ekor int
  created_at timestamp
  updated_at timestamp
}

Table pemberian_pakan_sisa_pakan {
  id biginteger [PK, increment]
  perhitungan_pakan_id biginteger [Ref : > perhitungan_pakan.id]
  flock_id int [Ref : > flock.id]
  sisa_pakan_per_flock_kg decimal(10,2)
  created_at timestamp
  updated_at timestamp
}

Table produksi_telur {
  id biginteger [PK, increment]
  flock_id int [Ref : > flock.id]
  pic_user_id biginteger [Ref : > users.id]
  tanggal date
  usia_ayam integer
  jumlah_telur_bagus integer
  jumlah_telur_putih integer
  jumlah_telur_reject integer
  berat_telur_bagus decimal(10,3)
  berat_telur_putih decimal(10,3)
  berat_telur_reject decimal(10,3)
  created_at timestamp
  updated_at timestamp
}

Table sampling_bobot_ayam {
  id biginteger [PK, increment]
  tanggal date
  kandang_id biginteger [Ref : > kandang.id]
  umur integer
  jumlah_ayam_saat_ini integer
  jumlah_ayam_yang_disampling integer
  created_at timestamp
  updated_at timestamp
}

Table sampling_bobot_ayam_per_ekor {
  id biginteger [PK, increment]
  sampling_bobot_ayam_id biginteger [Ref : > sampling_bobot_ayam.id]
  bobot_per_kg decimal
  created_at timestamp
  updated_at timestamp
}

Table jenis_disinfektan{
  id biginteger
  nama varchar
  created_at timestamp
  updated_at timestamp
}

Table jenis_treatment{
  id biginteger
  nama varchar
  created_at timestamp
  updated_at timestamp
}

Table metode_treatment{
  id biginteger
  nama varchar
  created_at timestamp
  updated_at timestamp
}

Table monitoring_kesehatan {
  id biginteger [PK, increment]
  kandang_id biginteger [Ref : > kandang.id]
  tanggal date
  tim_pelaksana varchar
  total_populasi_ayam varchar
  ayam_sehat integer
  ayam_sakit integer
  ayam_mati integer
  ayam_afkir integer
  detail_penyakit_ditemukan text
  umum_perilaku text
  umum_kondisi_bulu text
  umum_proporsi_tubuh text
  umum_nafsu_makan text
  umum_produktivitas_telur text
  lingkungan_suhu text
  lingkungan_kelembapan text
  lingkungan_kebersihan text
  detail_kondisi_umum text
  nekropsi_jumlah_ayam integer
  tindakan_pengobatan text
  tindakan_rekomendasi_jangka_panjang text
  tindakan_rekomendasi_jangka_pendek text
  evaluasi_efektivitas_pengobatan text
  evaluasi_catatan text
  dokumentasi json
  created_at timestamp
  updated_at timestamp
}

Table monitoring_kesehatan_dokumentasi{
  id int [PK, increment]
  monitoring_kesehatan_id int [Ref : > monitoring_kesehatan.id]
  path text
  keterangan text
  created_at timestamp
  updated_at timestamp
}

Table treatment {
  id int [PK, increment]
  kandang_id int [Ref: > kandang.id]
  tanggal date
  user_creator_id int [Ref: > users.id]
  created_at timestamp
  updated_at timestamp
}

Table treatment_jadwal {
  id int [PK, increment]
  treatment_id int [Ref: > treatment.id]
  jenis_treatment_id int [Ref: > jenis_treatment.id]
  metode_treatment_id int [Ref: > metode_treatment.id]
  merk_ovk varchar
  area varchar
  dosis varchar
  waktu time
  executed_at time
  executed_by int [Ref: > users.id]
  created_at timestamp
  updated_at timestamp
}

Table treatment_jadwal_flock {
  id int [PK, increment]
  treatment_jadwal_id int [Ref: - treatment_jadwal.id]
  created_at timestamp
  updated_at timestamp
}

Table satuan {
  id biginteger [PK, increment]
  nama varchar
  created_at timestamp
  updated_at timestamp
}

Table supplier {
  id biginteger [PK, increment]
  nama varchar
  badan_usaha varchar [null]
  kontak varchar [null]
  alamat text [null]
  lokasi text [null]
  created_at timestamp
  updated_at timestamp
}

Table kemasan {
  id biginteger [PK, increment]
  satuan_id biginteger [Ref : > satuan.id]
  nama varchar
  created_at timestamp
  updated_at timestamp
}

Table supplier_kemasan {
  id biginteger [PK, increment]
  supplier_id biginteger [Ref : > supplier.id]
  kemasan_id biginteger [Ref : > kemasan.id]
  kode_barang varchar
  harga decimal
  biaya_tambahan decimal [null]
  jenis_pengiriman enum(LOCO, FRANCO)
  created_at timestamp
  updated_at timestamp
}

Table kemasan_input {
  id biginteger [PK, increment]
  pic_user_id integer [Ref : > users.id]
  supplier_kemasan_id biginteger [Ref : > supplier_kemasan.id]
  tanggal datetime
  created_at timestamp
  updated_at timestamp
}

Table kemasan_input_dokumentasi {
  id int [PK, increment]
  kemasan_input_id int [Ref : > kemasan_input.id]
  filepath text
  created_at timestamp
  updated_at timestamp
}

Table kemasan_output {
  id biginteger [PK, increment]
  pic_user_id integer [Ref : > users.id]
  tanggal datetime
  created_at timestamp
  updated_at timestamp
}

Table kemasan_opname {
  id biginteger [PK, increment]
  pic_user_id integer [Ref : > users.id]
  tanggal datetime
  jumlah biginteger
  created_at timestamp
  updated_at timestamp
}

Table kemasan_inventory {
  id biginteger [PK, increment]
  tipe enum(input, output, opname)
  kemasan_input_id biginteger [null, Ref : > kemasan_input.id]
  kemasan_output_id biginteger [null, Ref : > kemasan_output.id]
  kemasan_opname_id biginteger [null, Ref : > kemasan_opname.id]
  kemasan_id biginteger [Ref : > kemasan.id]
  jumlah biginteger
  created_at timestamp
  updated_at timestamp
}