name: Deploy website on push
on:
  push:
    branches: [devel]
  workflow_dispatch:
jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: '22'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server-dir: './peternakan/'
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        port: ${{ secrets.FTP_PORT }}
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*
          **/.github*/**
          **/vendor/**
          **/storage/**
          **/node_modules/**
          **/.env